# Generated by Django 4.0.1 on 2022-03-21 02:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_type_remove_pet_type_pet_topic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='topic',
            new_name='type',
        ),
    ]
